name: Deploy PPPK JSON Server

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - dev
      - feat/**
env:
  IMAGE_NAME: "pppk-json-prod"
  IMAGE_VERSION: "latest"
  IMAGE_NAME_TAR: "pppk-json-prod.tar"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create network pppk_json_net
        run: docker network create pppk_json_net || echo "Network pppk_json_net already exists"

      - name: Create .env.prod file
        run: |
          echo "# the env configuration file for the project" >> .env.prod

      - name: "Build Docker Image"
        run: |
          docker compose -f compose.prod.yaml up -d

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: "Build Docker Image"
        run: |
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f compose.prod.yaml build pppk_json
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} -o ${{ env.IMAGE_NAME_TAR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: |
            compose.prod.yaml
            ${{ env.IMAGE_NAME_TAR }}

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: [pppk-json]

    environment: prod

    env:
      PATH_PROJECT: ${{ vars.PATH_PROJECT }}

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.PATH_PROJECT }}

      - name: Load Docker Image
        run: |
          cd ${{ env.PATH_PROJECT }}
          docker load -i ${{ env.IMAGE_NAME_TAR }}

      - name: List Docker images
        run: docker image ls

      - name: Run Production App with Docker Compose
        run: |
          cd ${{ env.PATH_PROJECT }} && echo $(pwd)
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f compose.prod.yaml up -d ${{ env.IMAGE_NAME}}

      - name: Cleanup unused Docker images
        run: docker image prune -af

      - name: List Docker images
        run: docker image ls

      - name: Remove tar file and List files in workspace
        run: |
          cd ${{ env.PATH_PROJECT }}
          rm ${{ env.IMAGE_NAME_TAR }} && ls -la

      - name: Check running containers
        run: docker ps -a
