name: Deploy PPPK JSON Server

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - dev
      - feat/**
env:
  IMAGE_NAME: "pppk-json-prod"
  IMAGE_VERSION: "latest"
  IMAGE_NAME_TAR: "pppk-json-prod.tar"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create network pppk_json_net
        run: docker network create pppk_json_net || echo "Network pppk_json_net already exists"

      - name: Create .env.prod file
        run: |
          echo "# the env configuration file for the project" >> .env.prod

      - name: "Build Docker Image"
        run: |
          docker compose -f compose.prod.yaml up -d


  